repos:

- repo: https://github.com/pycqa/isort
  rev: 6.0.1            # 26 фев 2025
  hooks:
    - id: isort
      args: ["--profile", "black"]   
      language_version: python3.12 


- repo: https://github.com/psf/black
  rev: 25.1.0           
  hooks:
    - id: black
      language_version: python3.12


- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.6         
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
      language_version: python3.12
